"""The provenance stamp every generated file carries.

The stamp is one HTML comment placed after the frontmatter (or on the first
line when there is none). It is invisible in rendered markdown, valid in every
kind of file the harness reads, and names everything a reader needs to judge
the file: the host and its version, the ``pkgskills`` version that rendered it, the
install mode, and the exact command that regenerates it.

A skill stub also carries the same two versions as frontmatter, under the
``metadata`` mapping the Agent Skills specification reserves for exactly this
(https://agentskills.io/specification#frontmatter-required), so a tool that
reads the frontmatter alone can still tell which release it is looking at.
The stamp remains the contract; the metadata mirrors it.

Every version token is masked before a drift comparison -- in the stamp and in
the metadata alike -- so a routine upgrade of either package never flags a
file whose content did not change.
"""

from __future__ import annotations

import re
from importlib import metadata

from pkgskills.host import MODES, Host, Mode

PREFIX = "<!-- generated by "

# The frontmatter metadata keys pkgskills owns. ``version`` is the host release the
# stub was rendered from -- the skill's own version, the spec's example key --
# and ``pkgskills-version`` is namespaced because it belongs to a second package.
METADATA_KEYS = ("version", "pkgskills-version")
INDENT = "  "


def pkgskills_version() -> str:
    """The installed ``pkgskills`` version, or ``0.0.0`` when the record is absent."""
    try:
        return metadata.version("pkgskills")
    except metadata.PackageNotFoundError:
        return "0.0.0"


def render_stamp(host: Host, mode: Mode) -> str:
    """The stamp line for ``host`` in ``mode``."""
    return (
        f"{PREFIX}{host.dist} {host.resolved_version()} "
        f"via pkgskills {pkgskills_version()} "
        f"(mode={mode}); do not edit. Regenerate with: "
        f"{host.install_command(mode, force=True)} -->"
    )


def metadata_lines(host: Host) -> list[str]:
    """The indented ``metadata`` entries a stub declares, in spec order.

    Both values are quoted: a version is a string, and an unquoted ``1.0``
    would otherwise read back as a float.
    """
    return [
        f'{INDENT}version: "{host.resolved_version()}"',
        f'{INDENT}pkgskills-version: "{pkgskills_version()}"',
    ]


def _line_re(dist: str) -> re.Pattern[str]:
    return re.compile(
        rf"(?m)^{re.escape(PREFIX)}{re.escape(dist)} (\S+) via pkgskills (\S+) "
        rf"\(mode=({'|'.join(MODES)})\)"
    )


_ANY_RE = re.compile(rf"(?m)^{re.escape(PREFIX)}(\S+) ")

_META_RE = re.compile(
    rf'(?m)^{INDENT}({"|".join(re.escape(key) for key in METADATA_KEYS)}): "[^"\n]*"$'
)


def is_stamped(text: str, host: Host) -> bool:
    """True when ``text`` carries a stamp line written for ``host``.

    Anchored to a whole line so a hand-written file that merely quotes the
    marker in prose is never mistaken for a generated one.
    """
    return _line_re(host.dist).search(text) is not None


def stamped_by(text: str) -> str | None:
    """The distribution named in ``text``'s stamp line, if any."""
    match = _ANY_RE.search(text)
    return match.group(1) if match else None


def stamped_mode(text: str, host: Host) -> Mode | None:
    """The mode recorded in ``text``'s stamp, or ``None`` when unstamped."""
    match = _line_re(host.dist).search(text)
    if match is None:
        return None
    mode = match.group(3)
    return "global" if mode == "global" else "local"


def mask_versions(text: str, host: Host) -> str:
    """``text`` with every version token replaced by ``*``.

    Both tokens in the stamp line, and the ``version``/``pkgskills-version`` entries
    a stub declares under ``metadata``. The metadata pattern is anchored to a
    two-space-indented line with a quoted value, which is the shape pkgskills
    writes; a rule or agent source that happens to declare a key of that name
    at that indent is masked too, and so cannot drift on that line alone.
    """

    def masked(match: re.Match[str]) -> str:
        return f"{PREFIX}{host.dist} * via pkgskills * (mode={match.group(3)})"

    text = _line_re(host.dist).sub(masked, text)
    return _META_RE.sub(rf'{INDENT}\1: "*"', text)


def place_stamp(front: str, stamp: str, body: str) -> str:
    """Splice ``stamp`` between a frontmatter block and a body.

    ``front`` is the raw block including its fences (or empty). The stamp sits
    on its own line separated by blank lines so the markdown around it renders
    unchanged.
    """
    body = body.lstrip("\n")
    return f"{front}\n{stamp}\n\n{body}" if front else f"{stamp}\n\n{body}"
