"""The provenance stamp every generated file carries.

The stamp is one HTML comment placed after the frontmatter (or on the first
line when there is none). It is invisible in rendered markdown, valid in every
kind of file the harness reads, and names everything a reader needs to judge
the file: the host and its version, the ``pkgskills`` version that rendered it, the
install mode, and the exact command that regenerates it.

The stamp is the sole home of that provenance. ``pkgskills`` writes nothing into
a stub's frontmatter ``metadata``: a source owns ``metadata.version``, which is
the skill's own version and passes through verbatim.

Both version tokens in the stamp are masked before a drift comparison, so a
routine upgrade of either package never flags a file whose content did not
change. A source-declared version is not masked -- when it changes, the stub
should drift.
"""

from __future__ import annotations

import re
from importlib import metadata

from pkgskills.host import MODES, Host, Mode

PREFIX = "<!-- generated by "


def pkgskills_version() -> str:
    """The installed ``pkgskills`` version, or ``0.0.0`` when the record is absent."""
    try:
        return metadata.version("pkgskills")
    except metadata.PackageNotFoundError:
        return "0.0.0"


def render_stamp(host: Host, mode: Mode) -> str:
    """The stamp line for ``host`` in ``mode``."""
    return (
        f"{PREFIX}{host.dist} {host.resolved_version()} "
        f"via pkgskills {pkgskills_version()} "
        f"(mode={mode}); do not edit. Regenerate with: "
        f"{host.install_command(mode, force=True)} -->"
    )


def _line_re(dist: str) -> re.Pattern[str]:
    return re.compile(
        rf"(?m)^{re.escape(PREFIX)}{re.escape(dist)} (\S+) via pkgskills (\S+) "
        rf"\(mode=({'|'.join(MODES)})\)"
    )


_ANY_RE = re.compile(rf"(?m)^{re.escape(PREFIX)}(\S+) ")


def is_stamped(text: str, host: Host) -> bool:
    """True when ``text`` carries a stamp line written for ``host``.

    Anchored to a whole line so a hand-written file that merely quotes the
    marker in prose is never mistaken for a generated one.
    """
    return _line_re(host.dist).search(text) is not None


def stamped_by(text: str) -> str | None:
    """The distribution named in ``text``'s stamp line, if any."""
    match = _ANY_RE.search(text)
    return match.group(1) if match else None


def stamped_mode(text: str, host: Host) -> Mode | None:
    """The mode recorded in ``text``'s stamp, or ``None`` when unstamped."""
    match = _line_re(host.dist).search(text)
    if match is None:
        return None
    mode = match.group(3)
    return "global" if mode == "global" else "local"


def mask_versions(text: str, host: Host) -> str:
    """``text`` with both version tokens in the stamp line replaced by ``*``.

    Only the stamp line. A ``metadata.version`` a source declares is the
    skill's own, so a change to it is a real content change and has to drift.
    """

    def masked(match: re.Match[str]) -> str:
        return f"{PREFIX}{host.dist} * via pkgskills * (mode={match.group(3)})"

    return _line_re(host.dist).sub(masked, text)


def place_stamp(front: str, stamp: str, body: str) -> str:
    """Splice ``stamp`` between a frontmatter block and a body.

    ``front`` is the raw block including its fences (or empty). The stamp sits
    on its own line separated by blank lines so the markdown around it renders
    unchanged.
    """
    body = body.lstrip("\n")
    return f"{front}\n{stamp}\n\n{body}" if front else f"{stamp}\n\n{body}"
