"""Tests for locating, writing, and drift-checking generated artifacts."""

from __future__ import annotations

import dataclasses
import os
from pathlib import Path

import pytest
from examplehost.cli import HOST as EXAMPLE
from solohost.cli import HOST as SOLO

from mli import artifacts as inst
from mli.host import Host
from mli.rendering import render
from mli.testing import Sandbox


def _statuses(host: Host, root: Path, mode: str | None = None) -> dict[str, str]:
    rows = inst.check(host, root, mode)  # type: ignore[arg-type]
    return {
        f"{row.artifact.kind.value}:{row.artifact.name}": row.status for row in rows
    }


def test_artifact_paths_per_mode_and_kind(box: Sandbox) -> None:
    skill, rule, agent = EXAMPLE.artifacts
    assert inst.artifact_path(EXAMPLE, skill, "global", box.repo) == (
        box.home / ".claude/skills/example/SKILL.md"
    )
    assert inst.artifact_path(EXAMPLE, skill, "local", box.repo) == (
        box.repo / ".claude/skills/example/SKILL.md"
    )
    assert inst.artifact_path(EXAMPLE, rule, "local", box.repo) == (
        box.repo / ".claude/rules/examplehost.md"
    )
    assert inst.artifact_path(EXAMPLE, agent, "local", box.repo) == (
        box.repo / ".claude/agents/example-reviewer.md"
    )


def test_find_repo_root_walks_up_and_falls_back(box: Sandbox, tmp_path: Path) -> None:
    sub = box.repo / "a" / "b"
    sub.mkdir(parents=True)
    assert inst.find_repo_root(sub) == box.repo
    bare = tmp_path / "nowhere" / "deep"
    bare.mkdir(parents=True)
    assert inst.find_repo_root(bare) == bare
    claude_only = tmp_path / "c"
    (claude_only / ".claude").mkdir(parents=True)
    assert inst.find_repo_root(claude_only / "x", EXAMPLE.harness) == claude_only


def test_check_reports_missing_before_install(box: Sandbox) -> None:
    rows = inst.check(EXAMPLE, box.repo)
    assert {row.status for row in rows} == {"missing"}
    assert all(row.mode == "global" for row in rows)


def test_install_local_writes_every_artifact_then_checks_ok(box: Sandbox) -> None:
    report = inst.install(EXAMPLE, box.repo, "local")
    assert len(report.written) == 3
    assert all(p.is_file() and box.repo in p.parents for p in report.written)
    assert _statuses(EXAMPLE, box.repo, "local") == {
        "skill:example": "ok",
        "rule:examplehost": "ok",
        "agent:example-reviewer": "ok",
    }
    # Without a mode, check judges whatever is installed, and finds the same.
    assert set(_statuses(EXAMPLE, box.repo).values()) == {"ok"}
    assert all(row.mode == "local" for row in inst.check(EXAMPLE, box.repo))


def test_install_global_lives_under_home(box: Sandbox) -> None:
    report = inst.install(SOLO, box.repo, "global")
    assert report.written == (box.home / ".claude/skills/use-solo/SKILL.md",)
    assert inst.installed_mode(SOLO, box.repo) == "global"


def test_installed_mode_prefers_global(box: Sandbox) -> None:
    assert inst.installed_mode(SOLO, box.repo) is None
    inst.install(SOLO, box.repo, "local")
    assert inst.installed_mode(SOLO, box.repo) == "local"
    inst.install(SOLO, box.repo, "global")
    assert inst.installed_mode(SOLO, box.repo) == "global"


def test_version_only_bump_is_not_drift(box: Sandbox) -> None:
    inst.install(EXAMPLE, box.repo, "local")
    bumped = dataclasses.replace(EXAMPLE, version="1.3.0")
    assert set(_statuses(bumped, box.repo).values()) == {"ok"}


def test_moved_copy_is_judged_by_its_location(box: Sandbox) -> None:
    skill = SOLO.skills[0]
    path = inst.artifact_path(SOLO, skill, "global", box.repo)
    path.parent.mkdir(parents=True)
    path.write_text(render(SOLO, skill, "local"), encoding="utf-8")
    row = inst.check_artifact(SOLO, skill, "global", box.repo)
    assert row.status == "drifted"
    assert "mode=local" in row.reason


def test_hand_edited_body_is_drift(box: Sandbox) -> None:
    (path,) = inst.install(SOLO, box.repo, "local").written
    path.write_text(path.read_text() + "\nextra line\n", encoding="utf-8")
    row = inst.check(SOLO, box.repo)[0]
    assert row.status == "drifted"
    assert row.reason == "content differs from the current render"


def test_foreign_shapes(box: Sandbox) -> None:
    skill = SOLO.skills[0]
    path = inst.artifact_path(SOLO, skill, "local", box.repo)
    path.parent.mkdir(parents=True)

    path.write_text("---\nname: use-solo\n---\nhand written\n", encoding="utf-8")
    row = inst.check_artifact(SOLO, skill, "local", box.repo)
    assert (row.status, row.reason) == (
        "foreign",
        "no stamp; hand-written or from an older release",
    )

    path.write_text("<!-- generated by otherpkg 1.0 via mli 0.1 (mode=local) -->\n")
    row = inst.check_artifact(SOLO, skill, "local", box.repo)
    assert row.status == "foreign"
    assert row.reason == "generated by otherpkg, not solohost"

    path.write_bytes(b"\xff\xfe\x00 not utf-8")
    assert inst.check_artifact(SOLO, skill, "local", box.repo).reason.startswith(
        "unreadable"
    )

    path.unlink()
    path.symlink_to(box.repo / "nowhere")
    row = inst.check_artifact(SOLO, skill, "local", box.repo)
    assert (row.status, row.reason) == ("foreign", "a symlink, not a plain file")

    path.unlink()
    path.mkdir()
    row = inst.check_artifact(SOLO, skill, "local", box.repo)
    assert (row.status, row.reason) == ("foreign", "a directory, not a file")


def test_prose_mention_of_the_marker_is_not_a_stamp(box: Sandbox) -> None:
    skill = SOLO.skills[0]
    path = inst.artifact_path(SOLO, skill, "local", box.repo)
    path.parent.mkdir(parents=True)
    path.write_text(
        "Files say <!-- generated by solohost 1 via mli 1 (mode=local) --> "
        "when generated.\n"
    )
    assert not inst.is_generated(path, SOLO)


def test_reinstall_over_own_copy_needs_no_force(box: Sandbox) -> None:
    inst.install(SOLO, box.repo, "local")
    inst.install(SOLO, box.repo, "local")
    assert _statuses(SOLO, box.repo) == {"skill:use-solo": "ok"}


def test_foreign_target_is_refused_before_anything_is_written(box: Sandbox) -> None:
    rule_path = inst.artifact_path(EXAMPLE, EXAMPLE.rules[0], "local", box.repo)
    rule_path.parent.mkdir(parents=True)
    rule_path.write_text("my own rule\n")
    with pytest.raises(inst.ForeignArtifactError) as excinfo:
        inst.install(EXAMPLE, box.repo, "local")
    assert excinfo.value.path == rule_path
    assert "no stamp" in excinfo.value.reason
    assert not inst.artifact_path(
        EXAMPLE, EXAMPLE.skills[0], "local", box.repo
    ).exists()
    assert rule_path.read_text() == "my own rule\n"


def test_force_replaces_a_symlink_without_writing_through(box: Sandbox) -> None:
    target = box.repo / "elsewhere.md"
    target.write_text("untouched\n")
    path = inst.artifact_path(SOLO, SOLO.skills[0], "local", box.repo)
    path.parent.mkdir(parents=True)
    path.symlink_to(target)
    with pytest.raises(inst.ForeignArtifactError):
        inst.install(SOLO, box.repo, "local")
    inst.install(SOLO, box.repo, "local", force=True)
    assert not path.is_symlink() and path.is_file()
    assert target.read_text() == "untouched\n"
    assert inst.is_generated(path, SOLO)


def test_global_install_removes_stale_local_copies_but_not_foreign_ones(
    box: Sandbox,
) -> None:
    inst.install(EXAMPLE, box.repo, "local")
    rule_local = inst.artifact_path(EXAMPLE, EXAMPLE.rules[0], "local", box.repo)
    rule_local.write_text("hand edited, but keeps no stamp\n")
    report = inst.install(EXAMPLE, box.repo, "global")
    removed = set(report.removed)
    assert inst.artifact_path(EXAMPLE, EXAMPLE.skills[0], "local", box.repo) in removed
    assert inst.artifact_path(EXAMPLE, EXAMPLE.agents[0], "local", box.repo) in removed
    assert rule_local not in removed and rule_local.exists()


def test_local_install_reports_a_shadowing_global_copy(box: Sandbox) -> None:
    inst.install(SOLO, box.repo, "global")
    report = inst.install(SOLO, box.repo, "local")
    assert report.shadowed == (
        inst.artifact_path(SOLO, SOLO.skills[0], "local", box.repo),
    )
    assert inst.shadowed_skills(SOLO, box.repo) == list(report.shadowed)


def test_check_without_mode_reports_both_locations(box: Sandbox) -> None:
    inst.install(SOLO, box.repo, "global")
    inst.install(SOLO, box.repo, "local")
    rows = inst.check(SOLO, box.repo)
    assert [row.mode for row in rows] == ["global", "local"]
    assert all(row.ok for row in rows)


def test_after_install_hook_receives_the_report(box: Sandbox) -> None:
    seen: list[inst.InstallReport] = []
    host = dataclasses.replace(SOLO, after_install=seen.append)
    report = inst.install(host, box.repo, "local")
    assert seen == [report]
    assert report.mode == "local" and report.root == box.repo


def test_no_stale_removal_when_repo_root_is_home(box: Sandbox) -> None:
    os.chdir(box.home)
    (box.home / ".git").mkdir()
    inst.install(SOLO, box.home, "local")
    report = inst.install(SOLO, box.home, "global")
    assert report.removed == ()
    assert inst.artifact_path(SOLO, SOLO.skills[0], "global", box.home).exists()
