"""Tests for wiring a host's commands into pre-commit."""

from __future__ import annotations

import dataclasses
import os
import shutil
import sys
from pathlib import Path

import pytest
from examplehost.cli import HOST as EXAMPLE
from solohost.cli import HOST as SOLO

from pkgskills import artifacts as inst
from pkgskills import precommit as pc
from pkgskills.host import ExtraCheck, Host, Mode
from pkgskills.proc import run
from pkgskills.testing import Sandbox

needs_git = pytest.mark.skipif(shutil.which("git") is None, reason="git not on PATH")

VALIDATE = pc.Hook(
    "solohost-validate",
    args=("validate",),
    name="validate things",
    files=r"^things/.*\.md$",
)
INDEX = pc.Hook(
    "solohost-index", stage="post-merge", args=("index", "."), always_run=True
)
HOOKS = (VALIDATE, INDEX)

# A stand-in for ``pre-commit install --hook-type <stage>``: writes the script
# pre-commit would, marker included, into the repo's hooks directory.
FAKE = """\
import sys
from pathlib import Path
stage = sys.argv[sys.argv.index("--hook-type") + 1]
hooks = Path(".git") / "hooks"
hooks.mkdir(exist_ok=True)
(hooks / stage).write_text("#!/bin/sh\\n# generated by pre-commit\\n")
"""


@pytest.fixture
def fake(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> tuple[str, ...]:
    # A global core.hooksPath on the developer's machine would otherwise leak
    # into every verdict below.
    monkeypatch.setenv("GIT_CONFIG_GLOBAL", os.devnull)
    monkeypatch.setenv("GIT_CONFIG_SYSTEM", os.devnull)
    script = tmp_path / "fake-pre-commit.py"
    script.write_text(FAKE, encoding="utf-8")
    return (sys.executable, str(script))


def _report(
    host: Host, root: Path, mode: Mode, previous: Mode | None = None
) -> inst.InstallReport:
    return inst.InstallReport(host, mode, root, previous=previous)


def test_hook_entry_is_derived_from_the_invocation() -> None:
    assert VALIDATE.entry("solohost") == "solohost validate"
    assert INDEX.entry("uv run solohost") == "uv run solohost index ."
    text = INDEX.render("solohost")
    assert "stages: [post-merge]" in text
    assert "always_run: true" in text
    assert "pass_filenames: false" in text
    assert "name: solohost-index" in text
    plain = VALIDATE.render("solohost")
    assert "stages:" not in plain and "always_run" not in plain
    assert "files: ^things/.*\\.md$" in plain


def test_precommit_command_follows_the_mode() -> None:
    assert pc.precommit_command(SOLO, "global") == ("pre-commit",)
    assert pc.precommit_command(SOLO, "local") == ("uv", "run", "pre-commit")
    custom = dataclasses.replace(SOLO, local_prefix="poetry run")
    assert pc.precommit_command(custom, "local") == ("poetry", "run", "pre-commit")


def test_wire_creates_the_config_and_registers_each_stage(
    box: Sandbox, fake: tuple[str, ...]
) -> None:
    report = pc.wire(_report(SOLO, box.repo, "local"), HOOKS, precommit=fake)
    assert report.created and report.changed
    assert report.added == ("solohost-validate", "solohost-index")
    assert report.resynced == ()
    assert dict(report.activation) == {
        "pre-commit": "activated",
        "post-merge": "activated",
    }
    text = (box.repo / ".pre-commit-config.yaml").read_text()
    assert text.startswith("repos:\n  - repo: local\n    hooks:\n")
    assert "entry: uv run solohost validate\n" in text
    assert "entry: uv run solohost index .\n" in text
    assert (box.repo / ".git/hooks/pre-commit").is_file()
    assert (box.repo / ".git/hooks/post-merge").is_file()

    # Idempotent: nothing to add, and both stages already live.
    again = pc.wire(_report(SOLO, box.repo, "local"), HOOKS, precommit=fake)
    assert not again.changed
    assert set(again.activation.values()) == {"already_active"}
    assert (box.repo / ".pre-commit-config.yaml").read_text() == text


def test_wire_appends_only_the_missing_hooks_to_an_existing_config(
    box: Sandbox, fake: tuple[str, ...]
) -> None:
    config = box.repo / ".pre-commit-config.yaml"
    existing = (
        "repos:\n  - repo: local\n    hooks:\n"
        "      - id: solohost-validate\n"
        "        entry: uv run solohost validate\n"
        "        language: system"  # no trailing newline, deliberately
    )
    config.write_text(existing, encoding="utf-8")
    report = pc.wire(_report(SOLO, box.repo, "local"), HOOKS, precommit=fake)
    assert not report.created
    assert report.added == ("solohost-index",)
    text = config.read_text()
    assert text.startswith(existing + "\n  - repo: local\n")
    assert text.count("id: solohost-validate") == 1
    assert "id: solohost-index" in text


def test_wire_resyncs_the_entry_only_on_a_mode_switch(
    box: Sandbox, fake: tuple[str, ...]
) -> None:
    config = box.repo / ".pre-commit-config.yaml"
    pc.wire(_report(SOLO, box.repo, "local"), HOOKS, precommit=fake)
    local_text = config.read_text()

    # A same-mode refresh, and a first install with no prior mode: the
    # committed entry is deliberate repo content and stays.
    for previous in ("global", None):
        report = pc.wire(
            _report(SOLO, box.repo, "global", previous=previous),
            HOOKS,
            precommit=fake,
        )
        assert report.resynced == ()
        assert config.read_text() == local_text

    # A genuine switch rewrites the entries that name the other mode.
    report = pc.wire(
        _report(SOLO, box.repo, "global", previous="local"), HOOKS, precommit=fake
    )
    assert report.resynced == ("solohost-validate", "solohost-index")
    assert report.added == ()
    text = config.read_text()
    assert "entry: solohost validate\n" in text
    assert "entry: solohost index .\n" in text
    assert "uv run solohost" not in text

    # An entry that names neither invocation was customized; a switch leaves it.
    custom = text.replace("entry: solohost validate\n", "entry: ./bin/validate\n")
    config.write_text(custom, encoding="utf-8")
    report = pc.wire(
        _report(SOLO, box.repo, "local", previous="global"), HOOKS, precommit=fake
    )
    assert report.resynced == ("solohost-index",)
    assert "entry: ./bin/validate\n" in config.read_text()


def test_wire_leaves_an_unreadable_config_alone(
    box: Sandbox, fake: tuple[str, ...]
) -> None:
    config = box.repo / ".pre-commit-config.yaml"
    config.write_bytes(b"\xff\xfe not utf-8")
    report = pc.wire(_report(SOLO, box.repo, "local"), HOOKS, precommit=fake)
    assert report.unreadable and not report.changed
    assert report.added == ()
    assert config.read_bytes() == b"\xff\xfe not utf-8"
    # Registration is still attempted: the entry may be in the unreadable text.
    assert set(report.activation.values()) == {"activated"}


def test_wire_without_activation_writes_the_config_only(
    box: Sandbox, fake: tuple[str, ...]
) -> None:
    report = pc.wire(
        _report(SOLO, box.repo, "local"), HOOKS, activate=False, precommit=fake
    )
    assert report.created
    assert set(report.activation.values()) == {"skipped"}
    assert not (box.repo / ".git/hooks").exists()


def test_wire_reports_why_a_stage_did_not_register(
    box: Sandbox, fake: tuple[str, ...], tmp_path: Path
) -> None:
    # Not a git repository: nowhere to register.
    bare = tmp_path / "bare"
    bare.mkdir()
    report = pc.wire(_report(SOLO, bare, "local"), HOOKS, precommit=fake)
    assert set(report.activation.values()) == {"no_git_repo"}

    # pre-commit missing, or failing.
    report = pc.wire(
        _report(SOLO, box.repo, "local"),
        HOOKS,
        precommit=("pkgskills-no-such-binary-exists",),
    )
    assert set(report.activation.values()) == {"unavailable"}
    report = pc.wire(
        _report(SOLO, box.repo, "local"),
        HOOKS,
        precommit=(sys.executable, "-c", "raise SystemExit(1)"),
    )
    assert set(report.activation.values()) == {"unavailable"}


@needs_git
def test_wire_reports_a_hookspath_block(box: Sandbox, fake: tuple[str, ...]) -> None:
    assert run(box.repo, ["git", "init", "-q"], capture_output=True).returncode == 0
    run(box.repo, ["git", "config", "core.hooksPath", "hooks"], capture_output=True)
    assert pc.hookspath_set(box.repo)
    report = pc.wire(_report(SOLO, box.repo, "local"), HOOKS, precommit=fake)
    assert set(report.activation.values()) == {"hookspath_blocked"}
    # The effective hooks dir is the configured one, so a script placed there
    # by other means still reads as registered.
    assert pc.hooks_dir(box.repo) == box.repo / "hooks"
    (box.repo / "hooks").mkdir()
    (box.repo / "hooks/pre-commit").write_text("# pre-commit\n")
    assert pc.registered(box.repo, "pre-commit")
    assert pc.hook_state(box.repo, VALIDATE) == "active"
    assert pc.hook_state(box.repo, INDEX) == "blocked"


def test_hooks_dir_falls_back_to_reading_git_itself(
    box: Sandbox, tmp_path: Path
) -> None:
    # A synthetic `.git` directory git refuses to answer for.
    assert pc.hooks_dir(box.repo) == box.repo / ".git/hooks"
    # A linked worktree's pointer file, relative and absolute.
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / ".git").write_text("gitdir: ../main/.git/worktrees/tree\n")
    assert pc.hooks_dir(tree) == tree / "../main/.git/worktrees/tree/hooks"
    (tree / ".git").write_text(f"gitdir: {tmp_path / 'main/.git'}\n")
    assert pc.hooks_dir(tree) == tmp_path / "main/.git/hooks"
    (tree / ".git").write_text("nonsense\n")
    assert pc.hooks_dir(tree) is None
    (tree / ".git").unlink()
    assert pc.hooks_dir(tree) is None


def test_a_hand_written_hook_script_is_not_our_registration(box: Sandbox) -> None:
    hooks = box.repo / ".git/hooks"
    hooks.mkdir()
    (hooks / "pre-commit").write_text("#!/bin/sh\nexit 0\n")
    assert not pc.registered(box.repo, "pre-commit")


def test_hook_state_reads_the_config_before_the_registration(
    box: Sandbox, fake: tuple[str, ...]
) -> None:
    assert pc.hook_state(box.repo, VALIDATE) == "missing"
    # pre-commit wired in for some other hook: still missing for ours.
    (box.repo / ".git/hooks").mkdir()
    (box.repo / ".git/hooks/pre-commit").write_text("# pre-commit\n")
    assert pc.hook_state(box.repo, VALIDATE) == "missing"
    pc.wire(_report(SOLO, box.repo, "local"), HOOKS, activate=False, precommit=fake)
    assert pc.hook_state(box.repo, VALIDATE) == "active"
    assert pc.hook_state(box.repo, INDEX) == "unregistered"
    (box.repo / ".git").rename(box.repo / "not-git")
    assert pc.hook_state(box.repo, INDEX) == "no_git_repo"


def test_checks_never_gate_and_name_the_fix(
    box: Sandbox, fake: tuple[str, ...]
) -> None:
    rows = pc.checks(SOLO, box.repo, "local", HOOKS)
    assert [row.label for row in rows] == [
        "hook solohost-validate",
        "hook solohost-index",
    ]
    assert {row.status for row in rows} == {"missing"}
    assert not any(row.gates for row in rows)
    assert "run `uv run solohost install --local`" in rows[0].note

    pc.wire(_report(SOLO, box.repo, "local"), HOOKS, activate=False, precommit=fake)
    rows = pc.checks(SOLO, box.repo, None, HOOKS)
    assert {row.status for row in rows} == {"unregistered"}
    # No mode given and nothing installed: the host's default names the fix.
    assert "`pre-commit install --hook-type pre-commit`" in rows[0].note
    assert "`pre-commit install --hook-type post-merge`" in rows[1].note
    rows = pc.checks(SOLO, box.repo, "local", HOOKS, precommit=("pc",))
    assert "`pc install --hook-type pre-commit`" in rows[0].note

    pc.wire(_report(SOLO, box.repo, "local"), HOOKS, precommit=fake)
    rows = pc.checks(SOLO, box.repo, "local", HOOKS)
    assert {row.status for row in rows} == {"active"}
    assert all(row.note == "" for row in rows)

    (box.repo / ".git").rename(box.repo / "not-git")
    rows = pc.checks(SOLO, box.repo, "local", HOOKS)
    assert {row.status for row in rows} == {"no_git_repo"}
    assert "no git repository" in rows[0].note


@needs_git
def test_checks_note_a_hookspath_block(box: Sandbox, fake: tuple[str, ...]) -> None:
    run(box.repo, ["git", "init", "-q"], capture_output=True)
    run(box.repo, ["git", "config", "core.hooksPath", "hooks"], capture_output=True)
    (box.repo / ".pre-commit-config.yaml").write_text("repos: []\n# solohost-index\n")
    (row,) = pc.checks(SOLO, box.repo, "local", (INDEX,))
    assert row.status == "blocked"
    assert "core.hooksPath" in row.note


def test_add_dependency_is_best_effort(box: Sandbox) -> None:
    assert not pc.add_dependency(box.repo, "pkgskills-no-such-binary-exists")
    assert not pc.add_dependency(box.repo, f"{sys.executable} -c raise")
    assert pc.add_dependency(box.repo, f"{sys.executable} -c pass")


def test_wiring_from_after_install_end_to_end(
    box: Sandbox, fake: tuple[str, ...]
) -> None:
    seen: list[pc.HookReport] = []

    def after(report: inst.InstallReport) -> None:
        seen.append(pc.wire(report, HOOKS, precommit=fake))

    def extras(host: Host, root: Path, mode: Mode | None) -> list[ExtraCheck]:
        return pc.checks(host, root, mode, HOOKS, precommit=fake)

    host = dataclasses.replace(SOLO, after_install=after, extra_checks=extras)
    inst.install(host, box.repo, "local")
    assert seen[-1].created
    assert (
        "entry: uv run solohost validate"
        in (box.repo / ".pre-commit-config.yaml").read_text()
    )
    # A switch to global, seen through InstallReport.previous, resyncs.
    inst.install(host, box.repo, "global")
    assert seen[-1].resynced == ("solohost-validate", "solohost-index")
    assert (
        "entry: solohost validate" in (box.repo / ".pre-commit-config.yaml").read_text()
    )
    assert {row.status for row in pc.checks(EXAMPLE, box.repo, None, HOOKS)} == {
        "active"
    }
