"""Tests for the shared command grammar, driven through the example hosts."""

from __future__ import annotations

import dataclasses
import os
import subprocess
import sys
from pathlib import Path

import pytest
from examplehost.cli import HOST as EXAMPLE
from examplehost.cli import app as example_app
from solohost.cli import HOST as SOLO
from solohost.cli import app as solo_app
from typer.testing import CliRunner

from mli import artifacts as inst
from mli.cli import typer_app
from mli.host import ExtraCheck, Host, Mode
from mli.rendering import render
from mli.testing import Sandbox

runner = CliRunner()
FIXTURES = Path(__file__).parent / "fixtures"


def test_host_keeps_its_own_commands(box: Sandbox) -> None:
    result = runner.invoke(example_app, ["hello"])
    assert result.exit_code == 0
    assert "hello from examplehost" in result.output


def test_skill_list(box: Sandbox) -> None:
    result = runner.invoke(example_app, ["skill", "--list"])
    assert result.exit_code == 0
    assert result.output.split() == ["add", "close"]


def test_skill_prints_body_from_the_package_without_a_stub(box: Sandbox) -> None:
    result = runner.invoke(example_app, ["skill", "add"])
    assert result.exit_code == 0
    assert result.output.startswith("# add\n")
    assert "ADD-BODY-SENTINEL" in result.output
    assert "name: add" not in result.output
    assert "examplehost validate ." in result.output
    assert "uv run" not in result.output


def test_skill_renders_cli_for_the_installed_mode(box: Sandbox) -> None:
    inst.install(EXAMPLE, box.repo, "local")
    result = runner.invoke(example_app, ["skill", "add"])
    assert "uv run examplehost validate ." in result.output


def test_skill_without_name_on_a_dispatcher_is_an_error(box: Sandbox) -> None:
    result = runner.invoke(example_app, ["skill"])
    assert result.exit_code == 1
    assert "name one of: add, close" in result.output


def test_unknown_skill_is_an_error(box: Sandbox) -> None:
    result = runner.invoke(example_app, ["skill", "nope"])
    assert result.exit_code == 1
    assert "unknown skill 'nope'" in result.output


def test_single_skill_host_prints_without_a_name_and_leaves_cli_alone(
    box: Sandbox,
) -> None:
    result = runner.invoke(solo_app, ["skill"])
    assert result.exit_code == 0
    assert "SOLO-BODY-SENTINEL" in result.output
    assert "{cli}" in result.output


def test_rule_and_agent_print_without_a_stamp(box: Sandbox) -> None:
    rule = runner.invoke(example_app, ["rule"])
    assert rule.exit_code == 0
    assert rule.output.startswith("# Things in this repo")
    assert "generated by" not in rule.output
    assert "`examplehost validate`" in rule.output
    agent = runner.invoke(example_app, ["agent", "example-reviewer"])
    assert agent.output.startswith("---\nname: example-reviewer\n")
    assert "AGENT-BODY-SENTINEL" in agent.output
    listing = runner.invoke(example_app, ["agent", "--list"])
    assert listing.output.strip() == "example-reviewer"


def test_single_skill_host_has_no_rule_or_agent_commands(box: Sandbox) -> None:
    assert runner.invoke(solo_app, ["rule"]).exit_code != 0
    assert runner.invoke(solo_app, ["agent"]).exit_code != 0


def test_install_local_writes_and_narrates(box: Sandbox) -> None:
    result = runner.invoke(example_app, ["install", "--local"])
    assert result.exit_code == 0, result.output
    assert "wrote .claude/skills/example/SKILL.md" in result.output
    assert "wrote .claude/rules/examplehost.md" in result.output
    assert "wrote .claude/agents/example-reviewer.md" in result.output
    assert (box.repo / ".claude/skills/example/SKILL.md").is_file()


def test_install_defaults_to_global_and_warns_when_cli_is_off_path(
    box: Sandbox,
) -> None:
    result = runner.invoke(solo_app, ["install"])
    assert result.exit_code == 0, result.output
    assert (box.home / ".claude/skills/use-solo/SKILL.md").is_file()
    assert "not on PATH" in result.output


def test_check_reports_each_status_and_exit_codes(box: Sandbox) -> None:
    before = runner.invoke(solo_app, ["install", "--check"])
    assert before.exit_code == 1
    assert "missing" in before.output
    assert "repair: solohost install --force" in before.output

    runner.invoke(solo_app, ["install", "--local"])
    ok = runner.invoke(solo_app, ["install", "--check"])
    assert ok.exit_code == 0, ok.output
    assert "ok      local  .claude/skills/use-solo/SKILL.md" in ok.output
    assert "solohost 0.9.0 via mli" in ok.output

    stub = box.repo / ".claude/skills/use-solo/SKILL.md"
    stub.write_text(stub.read_text() + "tampered\n")
    drifted = runner.invoke(solo_app, ["install", "--check"])
    assert drifted.exit_code == 1
    assert "drifted" in drifted.output
    assert "repair: uv run solohost install --local --force" in drifted.output


def test_check_gates_on_a_stale_local_copy_and_points_at_removal(
    box: Sandbox,
) -> None:
    inst.install(EXAMPLE, box.repo, "global")
    rule = inst.artifact_path(EXAMPLE, EXAMPLE.rules[0], "local", box.repo)
    rule.parent.mkdir(parents=True)
    rule.write_text(render(EXAMPLE, EXAMPLE.rules[0], "local"), encoding="utf-8")

    result = runner.invoke(example_app, ["install", "--check"])
    assert result.exit_code == 1
    assert "stale   local  .claude/rules/examplehost.md" in result.output
    assert "remove: .claude/rules/examplehost.md" in result.output
    # Rewriting the file is not the repair, so no local reinstall is suggested.
    assert "install --local --force" not in result.output

    rule.unlink()
    assert runner.invoke(example_app, ["install", "--check"]).exit_code == 0


def test_extra_checks_share_the_table_and_only_gate_when_they_say_so(
    box: Sandbox,
) -> None:
    seen: list[tuple[Path, str | None]] = []

    def extras(host: Host, root: Path, mode: Mode | None) -> list[ExtraCheck]:
        seen.append((root, mode))
        return [
            ExtraCheck("hook", "active", gates=False),
            ExtraCheck("gitattr", "missing", gates=True, note="run the wiring step"),
        ]

    host = dataclasses.replace(SOLO, extra_checks=extras)
    inst.install(host, box.repo, "local")
    app = typer_app(host)

    result = runner.invoke(app, ["install", "--check"])
    assert seen == [(box.repo, None)]
    assert "ok      local  .claude/skills/use-solo/SKILL.md" in result.output
    assert "active         hook" in result.output
    assert "missing        gitattr" in result.output
    assert "note: run the wiring step" in result.output
    assert result.exit_code == 1

    # The same rows, none of them gating: reported, and the check still passes.
    quiet = dataclasses.replace(
        SOLO,
        extra_checks=lambda h, r, m: [ExtraCheck("hook", "absent", gates=False)],
    )
    passing = runner.invoke(typer_app(quiet), ["install", "--check"])
    assert "absent         hook" in passing.output
    assert passing.exit_code == 0


def test_check_writes_nothing(box: Sandbox) -> None:
    runner.invoke(solo_app, ["install", "--check"])
    assert not (box.repo / ".claude").exists()
    assert not (box.home / ".claude").exists()


def test_check_local_narrows_to_the_repo_copy(box: Sandbox) -> None:
    runner.invoke(solo_app, ["install"])
    result = runner.invoke(solo_app, ["install", "--local", "--check"])
    assert result.exit_code == 1
    assert "missing local" in result.output


def test_refuses_a_hand_written_file_without_force(box: Sandbox) -> None:
    stub = box.repo / ".claude/skills/use-solo/SKILL.md"
    stub.parent.mkdir(parents=True)
    stub.write_text("mine\n")
    result = runner.invoke(solo_app, ["install", "--local"])
    assert result.exit_code == 1
    assert "refusing to overwrite" in result.output
    assert stub.read_text() == "mine\n"
    forced = runner.invoke(solo_app, ["install", "--local", "--force"])
    assert forced.exit_code == 0
    assert inst.is_generated(stub, EXAMPLE) is False
    assert "generated by solohost" in stub.read_text()


def test_install_local_from_a_subdirectory_targets_the_repo_root(
    box: Sandbox, monkeypatch: pytest.MonkeyPatch
) -> None:
    sub = box.repo / "docs" / "deep"
    sub.mkdir(parents=True)
    monkeypatch.chdir(sub)
    result = runner.invoke(solo_app, ["install", "--local"])
    assert result.exit_code == 0, result.output
    assert (box.repo / ".claude/skills/use-solo/SKILL.md").is_file()
    assert not (sub / ".claude").exists()


def test_local_install_notes_a_shadowing_global_copy(box: Sandbox) -> None:
    runner.invoke(solo_app, ["install"])
    result = runner.invoke(solo_app, ["install", "--local"])
    assert result.exit_code == 0
    assert "shadows the per-repo stub" in result.output


def test_squatting_file_in_the_parent_path_is_reported_cleanly(box: Sandbox) -> None:
    (box.repo / ".claude").mkdir()
    (box.repo / ".claude/skills").write_text("not a directory\n")
    result = runner.invoke(solo_app, ["install", "--local"])
    assert result.exit_code == 1
    assert "cannot write" in result.output


def test_skill_survives_a_non_utf8_stdout(box: Sandbox) -> None:
    env = dict(os.environ)
    env["PYTHONIOENCODING"] = "cp1252"
    env["PYTHONPATH"] = os.pathsep.join(
        [str(FIXTURES), str(Path(__file__).parents[1]), env.get("PYTHONPATH", "")]
    )
    proc = subprocess.run(
        [
            sys.executable,
            "-c",
            "from examplehost.cli import app; app()",
            "skill",
            "add",
        ],
        capture_output=True,
        env=env,
        cwd=box.repo,
        check=False,
    )
    assert proc.returncode == 0, proc.stderr.decode(errors="replace")
    assert b"ADD-BODY-SENTINEL" in proc.stdout
    assert b"Traceback" not in proc.stderr
